import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class shoppingListDisplayGUI extends JFrame {

    private JPanel mainPanel;
    private JLabel currentShoppingList;
    private JList<String> itemDisplayList;


    public shoppingListDisplayGUI(String title, shoppingList shoppingList) {
        super(title);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setContentPane(mainPanel);
        this.itemDisplayList.setModel(shoppingList.getAllItems());
//        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
//        GraphicsDevice defaultScreen = ge.getDefaultScreenDevice();
//        Rectangle rect = defaultScreen.getDefaultConfiguration().getBounds();
//        this.setLocation((int) rect.getMaxX() - this.getWidth(), 0);
        this.pack();
    }

    public shoppingListDisplayGUI(shoppingList list) {
        this.itemDisplayList.setModel(list.getAllItems());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        currentShoppingList = new JLabel();
        currentShoppingList.setHorizontalAlignment(0);
        currentShoppingList.setHorizontalTextPosition(0);
        currentShoppingList.setText("Your Current Shopping List ");
        mainPanel.add(currentShoppingList, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        itemDisplayList = new JList();
        mainPanel.add(itemDisplayList, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(300, 800), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
